// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOMCvwyjqF_Z2T-cL1JqFYExP_MAJY3I',
    appId: '1:374963405207:web:741b6413a47c6ac91384d2',
    messagingSenderId: '374963405207',
    projectId: 'todolist-29a2f',
    authDomain: 'todolist-29a2f.firebaseapp.com',
    storageBucket: 'todolist-29a2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvt61kIz1SkwPeASa2blZx7cj12k2szHE',
    appId: '1:374963405207:android:63a4c2fcc50b10581384d2',
    messagingSenderId: '374963405207',
    projectId: 'todolist-29a2f',
    storageBucket: 'todolist-29a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSE_IHpN7fJJW84WKW9kcVvnhDYdLWnQ0',
    appId: '1:374963405207:ios:62f0f7e2c06324401384d2',
    messagingSenderId: '374963405207',
    projectId: 'todolist-29a2f',
    storageBucket: 'todolist-29a2f.appspot.com',
    iosClientId: '374963405207-n2dgvf3v35bppt785au0gat7umnk7dh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSE_IHpN7fJJW84WKW9kcVvnhDYdLWnQ0',
    appId: '1:374963405207:ios:62f0f7e2c06324401384d2',
    messagingSenderId: '374963405207',
    projectId: 'todolist-29a2f',
    storageBucket: 'todolist-29a2f.appspot.com',
    iosClientId: '374963405207-n2dgvf3v35bppt785au0gat7umnk7dh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
